import { Building, CodexEntry, Enemy, Hero, Rank } from './types';

// ---------- RANKS ----------
export const RANKS: Rank[] = [
  { name: 'Sprout Healer', xpRequired: 0 },
  { name: 'Field Healer', xpRequired: 100 },
  { name: 'Ward Healer', xpRequired: 250 },
  { name: 'Clinical Guardian', xpRequired: 500 },
  { name: 'Codex Adept', xpRequired: 850 },
  { name: 'Master Healer', xpRequired: 1300 },
  { name: 'Mythic Clinician', xpRequired: 2000 },
];

// ---------- HEROES ----------
export const HEROES: Hero[] = [
  {
    id: 'novice_guardian',
    name: 'Novice Guardian',
    title: 'Apprentice Stabilizer',
    rarity: 3,
    role: 'Stabilizer',
    element: 'River',
    description: 'A vigilant med-surg healer who shores up vitals before the storm breaks.',
    faction: 'Air Temple',
    quote: 'Breathe. I am here. Let the air find you again.',
    backstory: 'Trained in the med-surg wards where oxygen crises strike without warning, this guardian learned to act before the crisis peaks.',
    bestAgainst: 'Air',
    medicalFocus: 'Respiratory distress, oxygenation, patient stabilization',
    bondLevel: 0,
    bondExp: 0,
    skills: [
      { id: 'breath_of_dawn', name: 'Breath of Dawn', type: 'stabilize', systemType: 'Air', cost: 1, description: 'Restore oxygenation. +14 Stability, -10 Corruption (Air).', shortEffect: 'Air Treatment • +14 Stability · -10 Corruption', rpgDescription: 'A bright breath restores oxygen flow to the fading Air Crystal, pushing back the respiratory corruption.', beginnerExplanation: 'This supports breathing and oxygen — directly fighting the airway problem.', nclexExplanation: 'Oxygenation support is a direct counter to respiratory distress. Positioning, supplemental oxygen, and airway management reduce the disease burden.', stabilize: 14, strike: 10 },
      { id: 'lantern_of_clues', name: 'Lantern of Clues', type: 'scout', systemType: 'Universal', cost: 1, description: 'Reveal one hidden clue.', shortEffect: 'Scout • Reveal Hidden Clue', rpgDescription: 'A lantern of insight reveals what the corruption tried to hide.', beginnerExplanation: 'Look closer to find the important clue.', nclexExplanation: 'Assessment data helps the nurse recognize relevant cues before choosing interventions.', reveal: 1 },
      { id: 'rapid_response', name: 'Rapid Response', type: 'stabilize', systemType: 'Universal', cost: 2, description: 'Emergency support. +26 Stability.', shortEffect: 'Stabilize • +26 Stability', rpgDescription: 'The healer surges in with practiced calm — the patient pulls back from the edge.', beginnerExplanation: 'A big push of support when the patient is in trouble.', nclexExplanation: 'Recognize deterioration and escalate care. Rapid intervention can stabilize an acutely unstable patient.', stabilize: 26 },
    ],
  },
  {
    id: 'night_watcher',
    name: 'Night Watcher',
    title: 'Vigil of the Ward',
    rarity: 3,
    role: 'Stabilizer',
    element: 'River',
    description: 'Patrols the night shift, catching subtle deterioration before it cascades.',
    skills: [
      { id: 'vital_ward', name: 'Vital Ward', type: 'scout', systemType: 'Universal', cost: 1, description: 'Reveal a clue and steady the patient.', shortEffect: 'Scout • Reveal + Stabilize', rpgDescription: 'A watchful ward steadies the patient while clues surface.', beginnerExplanation: 'A careful check that also helps the patient feel better.', nclexExplanation: 'Frequent reassessment can catch early changes and prompt timely interventions.', reveal: 1, stabilize: 8 },
      { id: 'rally_bell', name: 'Rally Bell', type: 'command', systemType: 'Universal', cost: 2, description: 'Summon support. -20 Corruption, +10 Stability.', shortEffect: 'Command • -20 Corruption · +10 Stability', rpgDescription: 'A silver bell summons nearby healers to steady the crisis.', beginnerExplanation: 'Call for help when the situation is getting worse — a coordinated response hits harder.', nclexExplanation: 'Escalation is appropriate when patient status is unstable, worsening, or beyond what can be safely managed alone. A timely call directly reduces disease burden.', strike: 20, stabilize: 10 },
    ],
  },
  {
    id: 'apprentice_seer',
    name: 'Apprentice Seer',
    title: 'Reader of Cues',
    rarity: 3,
    role: 'Assessor',
    element: 'Mind',
    description: 'Sees patterns others miss. Cues sing to her like distant bells.',
    faction: 'Codex Sanctum',
    quote: 'Every symptom is a sentence. Read them all before you act.',
    backstory: 'A clinical scholar who mastered assessment before treatment, believing that accurate cue recognition prevents more harm than any intervention.',
    bestAgainst: 'Mind',
    medicalFocus: 'Clinical assessment, pattern recognition, cue analysis',
    bondLevel: 0,
    bondExp: 0,
    skills: [
      { id: 'pattern_sight', name: 'Pattern Sight', type: 'analyze', systemType: 'Universal', cost: 1, description: 'Reveal 2 hidden clues. Pattern recognition guides a precise counter (-8 Corruption).', shortEffect: 'Analyze • Reveal 2 Clues · -8 Corruption', rpgDescription: 'Threads of the Codex reveal the pattern — and the Seer strikes where it hurts most.', beginnerExplanation: 'Find the problem and act on what you see.', nclexExplanation: 'Recognizing clinical patterns helps analyze cues and select targeted interventions — the right action at the right time reduces the disease burden.', reveal: 2, strike: 8 },
      { id: 'focused_lens', name: 'Focused Lens', type: 'analyze', systemType: 'Universal', cost: 2, description: 'Reveal all hidden clues and strike 12.', shortEffect: 'Analyze • Reveal All + Strike 12', rpgDescription: 'A crystal lens sharpens the healer’s focus and prepares the next move.', beginnerExplanation: 'A careful check makes your next correct move stronger.', nclexExplanation: 'Focused assessment helps connect symptoms to priority problems and supports safer clinical decision-making.', reveal: 99, strike: 12 },
    ],
  },
  {
    id: 'junior_warden',
    name: 'Junior Warden',
    title: 'Keeper of Safety',
    rarity: 3,
    role: 'Coordinator',
    element: 'Protection',
    description: 'Holds the line. Falls do not happen on her watch.',
    faction: 'Protection Wall',
    quote: 'Prevention is not passive. Safety is the sharpest intervention.',
    backstory: 'Forged in the prevention wards, the Junior Warden knows that the best outcome is the one where harm never reaches the patient.',
    bestAgainst: 'Protection',
    medicalFocus: 'Patient safety, fall prevention, infection control, harm reduction',
    bondLevel: 0,
    bondExp: 0,
    skills: [
      { id: 'safety_circle', name: 'Safety Circle', type: 'shield', systemType: 'Protection', cost: 1, description: 'Reduce next enemy damage by 50%.', shortEffect: 'Protection Shield • -50% Damage', rpgDescription: 'A protective circle prevents harm before it reaches the patient.', beginnerExplanation: 'Stop a dangerous event before it happens.', nclexExplanation: 'Patient safety includes fall prevention, medication safety, infection prevention, and reducing avoidable harm.', shield: 50 },
      { id: 'isolation_seal', name: 'Isolation Seal', type: 'command', systemType: 'Protection', cost: 2, description: 'Stop spread and counter infection. Shield 100%, -10 Corruption (vs Fire).', shortEffect: 'Protection Counter • Stop Spread · -10 Corruption', rpgDescription: 'A seal of protection seals off the infectious source and strikes at the corruption causing it.', beginnerExplanation: 'Stop germs from spreading AND help fight the infection.', nclexExplanation: 'Source control and transmission prevention directly reduce the infectious disease burden — isolation is not just defensive, it is a treatment.', blockSpread: true, shield: 100, strike: 10 },
    ],
  },
  {
    id: 'data_acolyte',
    name: 'Data Acolyte',
    title: 'Apprentice Weaver',
    rarity: 3,
    role: 'Analyst',
    element: 'Storm',
    description: 'Reads labs the way poets read sunsets.',
    faction: 'Storm Observatory',
    quote: 'The data does not lie. The question is whether you know how to read it.',
    backstory: 'A lab-trained analyst who understands that trending changes in data predict crises before they arrive.',
    bestAgainst: 'Storm',
    medicalFocus: 'Laboratory analysis, trend recognition, clinical data interpretation',
    bondLevel: 0,
    bondExp: 0,
    skills: [
      { id: 'threadwatch', name: 'Threadwatch', type: 'analyze', systemType: 'Universal', cost: 1, description: 'Reveal 1 clue and read the coming threat. Forewarned, the team braces — the next enemy attack deals 25% less damage.', shortEffect: 'Analyze • Reveal 1 · Brace −25% next hit', rpgDescription: 'The Weaver traces the next thread of deterioration before it snaps — and steadies the ward against it.', beginnerExplanation: 'Spotting what may get worse next lets you prepare — it softens the next hit.', nclexExplanation: 'Trending changes in assessment data can identify deterioration before a crisis occurs, letting the nurse intervene proactively.', reveal: 1, shield: 25 },
      { id: 'codex_link', name: 'Codex Link', type: 'scout', systemType: 'Universal', cost: 2, description: 'Reveal all hidden clues. Codex insight translates into precise action (-10 Corruption).', shortEffect: 'Analyze • Reveal All · -10 Corruption', rpgDescription: 'The revealed clues connect into a glowing Codex chain — and the Weaver strikes with precision.', beginnerExplanation: 'Use what you learned to fight the disease directly.', nclexExplanation: 'Clinical judgment requires connecting assessment cues to targeted interventions — complete data drives the right action and reduces disease burden.', reveal: 99, strike: 10 },
    ],
  },
  {
    id: 'village_caretaker',
    name: 'Village Caretaker',
    title: 'Hands of Comfort',
    rarity: 3,
    role: 'Educator',
    element: 'Growth',
    description: 'The first healer most patients ever meet. Steady, kind, present.',
    faction: 'Growth Sanctum',
    quote: 'A steady presence is the oldest medicine.',
    backstory: 'The Caretaker has seen more patients recover from kindness and consistency than from any spell. Basic care is the foundation everything else stands on.',
    bestAgainst: 'Growth',
    medicalFocus: 'Fundamental nursing care, comfort measures, patient education',
    bondLevel: 0,
    bondExp: 0,
    skills: [
      { id: 'guardians_touch', name: "Guardian's Touch", type: 'support', systemType: 'Universal', cost: 1, description: 'Steady support. +10 Stability, -10 Corruption.', shortEffect: 'Universal Treatment • +10 Stability · -10 Corruption', rpgDescription: 'A steadying pulse of healing energy restores balance and pushes back the corruption.', beginnerExplanation: 'Basic care helps the patient feel better and fights the problem.', nclexExplanation: 'Fundamental nursing care — repositioning, hygiene, comfort measures, and monitoring — has a real therapeutic effect that reduces disease burden over time.', stabilize: 10, strike: 10 },
      { id: 'reassess', name: 'Reassess', type: 'scout', systemType: 'Universal', cost: 1, description: 'Reveal one clue. Catching the gap in care reduces Corruption by 8.', shortEffect: 'Scout • Reveal Clue · -8 Corruption', rpgDescription: 'A patient eye returns to the bedside, finds what was missed, and corrects the course.', beginnerExplanation: 'Take another look — catching a missed step actively helps the patient recover.', nclexExplanation: 'Reassessment closes care gaps. Identifying a missed intervention or change in status directly reduces the disease burden.', reveal: 1, strike: 8 },
      { id: 'glucose_round', name: 'Glucose Round', type: 'strike', systemType: 'Energy', cost: 2, description: 'Follow glucose protocol. -16 Corruption (Energy). Reveal 1 clue.', shortEffect: 'Energy Counter • -16 Corruption · Reveal Clue', rpgDescription: 'The Caretaker reads the Energy Crystal and responds precisely — glucose protocol restores the balance that corruption stole.', beginnerExplanation: 'Check blood sugar and give glucose if low — this directly fights the energy problem.', nclexExplanation: 'Hypoglycemia management requires glucose monitoring and administration per protocol. This nurse-initiated action directly treats the underlying energy deficit.', strike: 16, reveal: 1 },
    ],
  },
  {
    id: 'storm_runner',
    name: 'Storm Runner',
    title: 'ER Trauma Sentinel',
    rarity: 4,
    role: 'Stabilizer',
    element: 'Fire',
    description: 'Sprints toward crisis when others retreat. Lives for the code.',
    skills: [
      { id: 'critical_response', name: 'Critical Response', type: 'stabilize', systemType: 'Universal', cost: 2, description: 'Massive stabilization. +28 Stability.', shortEffect: 'Stabilize • +28 Stability', rpgDescription: 'In the chaos, the runner becomes the calm — and the patient stabilizes.', beginnerExplanation: 'Big emergency support when seconds matter.', nclexExplanation: 'In acute deterioration, prioritize ABCs and rapid stabilization while escalating care.', stabilize: 28 },
      { id: 'river_surge', name: 'River Surge', type: 'strike', systemType: 'River', cost: 2, description: 'Strike 20 + stabilize 12. Risk: heart failure.', shortEffect: 'River Stabilize • BP Counter', rpgDescription: 'A healing current restores flow through the weakened River system.', beginnerExplanation: 'This supports circulation when blood pressure is low.', nclexExplanation: 'Hypotension and poor perfusion require prompt assessment and ordered fluid support — but be cautious in heart failure where overload worsens the patient.', strike: 20, stabilize: 12, risk: { ifSystem: 'River', penalty: 20, description: 'Aggressive fluids worsen pulmonary edema in Cardion.' } },
    ],
  },
  {
    id: 'infection_warden',
    name: 'Infection Warden',
    title: 'Sentinel of Containment',
    rarity: 4,
    role: 'Specialist',
    element: 'Fire',
    description: 'Walls of soap, isolation, and vigilance against the unseen.',
    skills: [
      { id: 'infection_scan', name: 'Infection Scan', type: 'scout', systemType: 'Fire', cost: 1, description: 'Reveal infection clues + strike 10.', shortEffect: 'Fire Scout • Reveal + Strike 10', rpgDescription: 'A practiced eye scans for the source of the corruption.', beginnerExplanation: 'Look for where the infection is coming from.', nclexExplanation: 'Source identification is critical for infection management. Look for wounds, lines, lungs, and urine as common sources.', reveal: 1, strike: 10 },
      { id: 'purity_mark', name: 'Purity Mark', type: 'strike', systemType: 'Fire', cost: 2, description: 'Antibiotic burst. Strike 26.', shortEffect: 'Fire Strike • -26 Corruption', rpgDescription: 'A cleansing mark burns away infectious corruption.', beginnerExplanation: 'This helps fight infection-type corruption.', nclexExplanation: 'Fever, chills, and spreading infection require recognition, infection control, ordered antimicrobial therapies, and monitoring for sepsis.', strike: 26 },
    ],
  },
  {
    id: 'wound_sage',
    name: 'Wound Sage',
    title: 'Mender of Skin and Tissue',
    rarity: 4,
    role: 'Specialist',
    element: 'Protection',
    description: 'Knows every layer of skin, every stage of healing.',
    skills: [
      { id: 'skin_shield', name: 'Skin Shield', type: 'shield', systemType: 'Protection', cost: 1, description: 'Prevent 45% damage next turn.', shortEffect: 'Protection Shield • -45% Damage', rpgDescription: 'A weave of healing knits the barrier before harm arrives.', beginnerExplanation: 'Protect the skin and body from harm.', nclexExplanation: 'Maintain skin integrity through positioning, pressure relief, and barrier care to prevent breakdown.', shield: 45 },
      { id: 'mend', name: 'Mend', type: 'strike', systemType: 'Protection', cost: 1, description: 'Wound treatment. +12 Stability, -12 Corruption.', shortEffect: 'Protection Treatment • +12 Stability · -12 Corruption', rpgDescription: 'Patient hands cleanse and close what was torn — the corruption loses its foothold.', beginnerExplanation: 'Treating the wound directly fights the problem causing harm.', nclexExplanation: 'Wound care is an active treatment: debridement, dressing changes, and infection control directly reduce the disease process and promote tissue recovery.', stabilize: 12, strike: 12 },
    ],
  },
  {
    id: 'mindkeeper',
    name: 'Mindkeeper',
    title: 'Anchor of the Restless Soul',
    rarity: 4,
    role: 'Specialist',
    element: 'Mind',
    description: 'Listens. Truly listens. Crisis softens in her presence.',
    skills: [
      { id: 'mind_anchor', name: 'Mind Anchor', type: 'cleanse', systemType: 'Mind', cost: 1, description: 'Calm and reorient the patient. +8 Stability, -12 Mind Corruption.', shortEffect: 'Mind Treatment • +8 Stability · -12 Corruption', rpgDescription: 'A steady voice anchors the patient — and the corruption of confusion loses its grip.', beginnerExplanation: 'Calming the patient actively fights Mind-type disease processes.', nclexExplanation: 'Therapeutic communication and de-escalation are active clinical interventions — they directly reduce the neurological and psychological disease burden in delirium and mental health crises.', stabilize: 8, strike: 12 },
      { id: 'error_ward', name: 'Error Ward', type: 'shield', systemType: 'Protection', cost: 2, description: 'Brace completely — the next enemy attack deals no damage (Shield 100%).', shortEffect: 'Protection Shield • Block Next Attack', rpgDescription: 'A warning rune flares and absorbs the next blow entirely.', beginnerExplanation: 'Fully shield the patient from the next hit.', nclexExplanation: 'Nurses must recognize unsafe orders, contraindications, and interventions that could worsen the patient.', shield: 100 },
    ],
  },
];

// ---------- ENEMIES ----------
export const ENEMIES: Enemy[] = [
  {
    id: 'air_sprite',
    name: 'Air Sprite Corruption',
    realWorld: 'Asthma exacerbation',
    primarySystem: 'Air',
    difficulty: 1,
    startingStability: 50,
    instability: 10,
    corruption: 80,
    weakSystem: 'Air',
    visibleClues: [
      { id: 'c1', label: 'Breathing Fast', detail: 'Respirations are quick and shallow.', hidden: false },
      { id: 'c2', label: 'O₂ Glow Dim', detail: 'SpO₂ 88% on room air.', hidden: false },
      { id: 'c3', label: 'Tripod Posture', detail: 'Sitting upright to breathe.', hidden: false },
    ],
    hiddenClues: [
      { id: 'h1', label: 'Wheezing', detail: 'Audible expiratory wheeze.', hidden: true },
    ],
    dangerTrigger: 'Respiratory failure',
    bestCounters: ['stabilize', 'scout'],
    teaches: ['oxygenation_basics', 'air_assessment'],
  },
  {
    id: 'river_sludge',
    name: 'River Sludge',
    realWorld: 'Hypovolemia / poor perfusion',
    primarySystem: 'River',
    difficulty: 1,
    startingStability: 60,
    instability: 5,
    corruption: 75,
    weakSystem: 'River',
    visibleClues: [
      { id: 'c1', label: 'Weak Pulse', detail: 'Thready radial pulse.', hidden: false },
      { id: 'c2', label: 'Pale Skin', detail: 'Cool, pale extremities.', hidden: false },
      { id: 'c3', label: 'Dizzy on Stand', detail: 'Orthostatic symptoms.', hidden: false },
    ],
    hiddenClues: [
      { id: 'h1', label: 'BP 88/52', detail: 'Hypotension confirmed.', hidden: true },
    ],
    dangerTrigger: 'Hypoperfusion shock',
    bestCounters: ['stabilize', 'strike'],
    teaches: ['circulation_basics'],
  },
  {
    id: 'energy_lock',
    name: 'Energy Lock',
    realWorld: 'Hypoglycemia',
    primarySystem: 'Energy',
    difficulty: 1,
    startingStability: 50,
    instability: 7,
    corruption: 70,
    weakSystem: 'Energy',
    visibleClues: [
      { id: 'c1', label: 'Cold Sweat', detail: 'Diaphoresis without fever.', hidden: false },
      { id: 'c2', label: 'Shakiness', detail: 'Fine tremor in hands.', hidden: false },
      { id: 'c3', label: 'Confusion', detail: 'Slow, hesitant responses.', hidden: false },
    ],
    hiddenClues: [
      { id: 'h1', label: 'Glucose 48', detail: 'BG critically low.', hidden: true },
    ],
    dangerTrigger: 'Loss of consciousness',
    bestCounters: ['stabilize', 'strike'],
    teaches: ['energy_basics', 'hypoglycemia_rules'],
  },
  {
    id: 'fire_imp',
    name: 'Fire Imp',
    realWorld: 'Localized infection',
    primarySystem: 'Fire',
    difficulty: 2,
    startingStability: 65,
    instability: 4,
    corruption: 85,
    weakSystem: 'Fire',
    visibleClues: [
      { id: 'c1', label: 'Fever 38.9°C', detail: 'Tactile warm forehead.', hidden: false },
      { id: 'c2', label: 'Localized Redness', detail: 'Cellulitis-like erythema.', hidden: false },
      { id: 'c3', label: 'Chills', detail: 'Rigors reported.', hidden: false },
    ],
    hiddenClues: [
      { id: 'h1', label: 'WBC 14k', detail: 'Leukocytosis.', hidden: true },
    ],
    dangerTrigger: 'Systemic spread',
    bestCounters: ['scout', 'strike', 'shield'],
    teaches: ['infection_basics'],
  },
  {
    id: 'septara_seed',
    name: 'Septara Seed',
    realWorld: 'Early sepsis',
    primarySystem: 'Fire',
    secondarySystem: 'River',
    difficulty: 3,
    startingStability: 45,
    instability: 8,
    corruption: 110,
    weakSystem: 'Fire',
    visibleClues: [
      { id: 'c1', label: 'Fever 39.2°C', detail: 'High fever, sustained.', hidden: false },
      { id: 'c2', label: 'HR 124', detail: 'Sinus tachycardia.', hidden: false },
      { id: 'c3', label: 'Confusion', detail: 'New-onset AMS.', hidden: false },
    ],
    hiddenClues: [
      { id: 'h1', label: 'BP 92/58', detail: 'Borderline hypotension.', hidden: true },
      { id: 'h2', label: 'Lactate 3.4', detail: 'Tissue hypoperfusion.', hidden: true },
    ],
    dangerTrigger: 'Septic shock',
    bestCounters: ['scout', 'strike', 'stabilize'],
    teaches: ['sepsis_recognition', 'systemic_infection'],
  },
  {
    id: 'cardion_echo',
    name: 'Cardion Echo',
    realWorld: 'Heart failure exacerbation',
    primarySystem: 'River',
    secondarySystem: 'Air',
    difficulty: 3,
    startingStability: 50,
    instability: 6,
    corruption: 100,
    weakSystem: 'River',
    visibleClues: [
      { id: 'c1', label: 'Crackles', detail: 'Bibasilar rales.', hidden: false },
      { id: 'c2', label: 'Leg Swelling', detail: '+2 pitting edema.', hidden: false },
      { id: 'c3', label: 'SOB', detail: 'Dyspnea on exertion.', hidden: false },
    ],
    hiddenClues: [
      { id: 'h1', label: 'Weight +3kg', detail: 'Rapid fluid retention.', hidden: true },
      { id: 'h2', label: 'BNP 1200', detail: 'Elevated.', hidden: true },
    ],
    dangerTrigger: 'Pulmonary flood',
    bestCounters: ['stabilize', 'cleanse', 'scout'],
    teaches: ['heart_failure_basics', 'fluid_balance'],
  },
  {
    id: 'glycora_spark',
    name: 'Glycora Spark',
    realWorld: 'Early DKA',
    primarySystem: 'Energy',
    secondarySystem: 'Storm',
    difficulty: 3,
    startingStability: 48,
    instability: 7,
    corruption: 105,
    weakSystem: 'Energy',
    visibleClues: [
      { id: 'c1', label: 'Glucose 486', detail: 'Severely elevated.', hidden: false },
      { id: 'c2', label: 'Thirst', detail: 'Polydipsia, dry mucous membranes.', hidden: false },
      { id: 'c3', label: 'Kussmaul Breathing', detail: 'Deep, rapid respirations.', hidden: false },
    ],
    hiddenClues: [
      { id: 'h1', label: 'K⁺ 3.2', detail: 'Borderline hypokalemia.', hidden: true },
      { id: 'h2', label: 'Ketones +++', detail: 'Heavy ketonuria.', hidden: true },
    ],
    dangerTrigger: 'Acid storm collapse',
    bestCounters: ['scout', 'stabilize', 'strike'],
    teaches: ['dka_basics', 'insulin_safety'],
  },
  {
    id: 'pulmora_wisp',
    name: 'Pulmora Wisp',
    realWorld: 'COPD exacerbation',
    primarySystem: 'Air',
    difficulty: 2,
    startingStability: 52,
    instability: 5,
    corruption: 90,
    weakSystem: 'Air',
    visibleClues: [
      { id: 'c1', label: 'Pursed-lip Breathing', detail: 'Working hard to exhale.', hidden: false },
      { id: 'c2', label: 'Barrel Chest', detail: 'Hyperinflated.', hidden: false },
      { id: 'c3', label: 'SpO₂ 86%', detail: 'Mild hypoxia.', hidden: false },
    ],
    hiddenClues: [
      { id: 'h1', label: 'CO₂ 58', detail: 'Hypercapnia.', hidden: true },
    ],
    dangerTrigger: 'Respiratory failure',
    bestCounters: ['stabilize', 'scout'],
    teaches: ['copd_basics'],
  },
  {
    id: 'electrox_flicker',
    name: 'Electrox Flicker',
    realWorld: 'Hyperkalemia',
    primarySystem: 'Storm',
    secondarySystem: 'River',
    difficulty: 3,
    startingStability: 55,
    instability: 6,
    corruption: 95,
    weakSystem: 'Storm',
    visibleClues: [
      { id: 'c1', label: 'Muscle Weakness', detail: 'Generalized weakness.', hidden: false },
      { id: 'c2', label: 'Peaked T waves', detail: 'EKG abnormality.', hidden: false },
      { id: 'c3', label: 'Tingling', detail: 'Paresthesias.', hidden: false },
    ],
    hiddenClues: [
      { id: 'h1', label: 'K⁺ 6.4', detail: 'Critical hyperkalemia.', hidden: true },
    ],
    dangerTrigger: 'Rhythm collapse',
    bestCounters: ['scout', 'cleanse', 'strike'],
    teaches: ['electrolyte_basics', 'potassium_rules'],
  },
  {
    id: 'mind_fog',
    name: 'Mind Fog',
    realWorld: 'Delirium',
    primarySystem: 'Mind',
    difficulty: 2,
    startingStability: 58,
    instability: 4,
    corruption: 80,
    weakSystem: 'Mind',
    visibleClues: [
      { id: 'c1', label: 'Disoriented', detail: 'Not oriented to time/place.', hidden: false },
      { id: 'c2', label: 'Agitation', detail: 'Pulling at lines.', hidden: false },
      { id: 'c3', label: 'Fluctuating LOC', detail: 'Sleep-wake reversal.', hidden: false },
    ],
    hiddenClues: [
      { id: 'h1', label: 'UTI suspected', detail: 'Cloudy urine, odor.', hidden: true },
    ],
    dangerTrigger: 'Injury / fall',
    bestCounters: ['shield', 'cleanse', 'scout'],
    teaches: ['delirium_basics', 'safety_first'],
  },
];

// ---------- WAVE AFFLICTIONS (small companion enemies that ride alongside a primary enemy) ----------
export const AFFLICTION_ENEMIES: Enemy[] = [
  {
    id: 'hypoxia_wisp',
    name: 'Hypoxia Wisp',
    realWorld: 'Worsening oxygen desaturation',
    primarySystem: 'Air',
    difficulty: 2,
    startingStability: 100,
    instability: 0,
    corruption: 30,
    weakSystem: 'Air',
    behaviorTag: 'hypoxia',
    isAffliction: true,
    visibleClues: [
      { id: 'c1', label: 'SpO₂ Dropping', detail: 'Saturation trending down each turn.', hidden: false },
    ],
    hiddenClues: [
      { id: 'h1', label: 'Accessory Muscle Use', detail: 'Working harder to breathe.', hidden: true },
    ],
    dangerTrigger: 'Silent hypoxia',
    bestCounters: ['stabilize', 'scout'],
    teaches: [],
  },
  {
    id: 'mucus_wisp',
    name: 'Mucus Wisp',
    realWorld: 'Airway obstruction from secretions',
    primarySystem: 'Air',
    difficulty: 2,
    startingStability: 100,
    instability: 0,
    corruption: 25,
    weakSystem: 'Air',
    behaviorTag: 'mucus',
    isAffliction: true,
    visibleClues: [
      { id: 'c1', label: 'Thick Secretions', detail: 'Airway partially clogged.', hidden: false },
    ],
    hiddenClues: [],
    dangerTrigger: 'Airway obstruction',
    bestCounters: ['cleanse', 'stabilize'],
    teaches: [],
  },
  {
    id: 'panic_wraith',
    name: 'Panic Wraith',
    realWorld: 'Anxiety-driven tachypnea',
    primarySystem: 'Mind',
    difficulty: 2,
    startingStability: 100,
    instability: 0,
    corruption: 20,
    weakSystem: 'Mind',
    behaviorTag: 'panic',
    isAffliction: true,
    visibleClues: [
      { id: 'c1', label: 'Racing Thoughts', detail: 'Fear amplifies every symptom.', hidden: false },
    ],
    hiddenClues: [],
    dangerTrigger: 'Panic spiral',
    bestCounters: ['cleanse', 'support'],
    teaches: [],
  },
  {
    id: 'wheeze_guard',
    name: 'Wheeze Guard',
    realWorld: 'Bronchospasm shielding the primary lesion',
    primarySystem: 'Air',
    difficulty: 2,
    startingStability: 100,
    instability: 0,
    corruption: 28,
    weakSystem: 'Air',
    behaviorTag: 'wheeze',
    isAffliction: true,
    visibleClues: [
      { id: 'c1', label: 'Diffuse Wheeze', detail: 'Bronchospasm across both fields.', hidden: false },
    ],
    hiddenClues: [],
    dangerTrigger: 'Bronchospasm cascade',
    bestCounters: ['stabilize', 'strike'],
    teaches: [],
  },
  {
    id: 'shock_spike',
    name: 'Shock Spike',
    realWorld: 'Acute hemodynamic instability',
    primarySystem: 'River',
    difficulty: 3,
    startingStability: 100,
    instability: 0,
    corruption: 35,
    weakSystem: 'River',
    behaviorTag: 'shock',
    isAffliction: true,
    visibleClues: [
      { id: 'c1', label: 'BP Crashing', detail: 'Pressure falling turn over turn.', hidden: false },
    ],
    hiddenClues: [
      { id: 'h1', label: 'Cap Refill >3s', detail: 'Poor peripheral perfusion.', hidden: true },
    ],
    dangerTrigger: 'Hemodynamic collapse',
    bestCounters: ['stabilize', 'strike'],
    teaches: [],
  },
];

// Only these primary enemies spawn with wave companions — all others remain single-enemy encounters.
export const WAVE_COMPANIONS: Record<string, string[]> = {
  septara_seed: ['shock_spike'],
  cardion_echo: ['hypoxia_wisp'],
  pulmora_wisp: ['mucus_wisp'],
  air_sprite: ['panic_wraith'],
  electrox_flicker: ['wheeze_guard'],
};

export function getWaveAdditionalEnemies(enemyId: string): Enemy[] {
  const ids = WAVE_COMPANIONS[enemyId];
  if (!ids || ids.length === 0) return [];
  return ids.map(id => AFFLICTION_ENEMIES.find(e => e.id === id)).filter((e): e is Enemy => !!e);
}

// ---------- CHAPTER 1 BOSS ----------
export const BOSS_LORD_IMBALANCE: Enemy = {
  id: 'lord_imbalance',
  name: 'Lord Imbalance',
  realWorld: 'Multi-system physiologic instability',
  primarySystem: 'River',
  secondarySystem: 'Mind',
  difficulty: 5,
  startingStability: 40,
  instability: 9,
  corruption: 180,
  stabilityResistance: 0.3, // hidden: Lord Imbalance shrugs off 30% of stabilization — the patient is hard to hold steady
  visibleClues: [
    { id: 'c1', label: 'Air Faltering', detail: 'SpO₂ trending down, RR 26.', hidden: false },
    { id: 'c2', label: 'River Weakening', detail: 'BP 96/60, HR 118.', hidden: false },
    { id: 'c3', label: 'Mind Slipping', detail: 'New confusion, lethargy.', hidden: false },
  ],
  hiddenClues: [
    { id: 'h1', label: 'Glucose 52', detail: 'Hypoglycemia compounding.', hidden: true },
    { id: 'h2', label: 'Temp 38.8', detail: 'Source unclear — infection?', hidden: true },
  ],
  dangerTrigger: 'Multi-organ collapse',
  bestCounters: ['scout', 'stabilize', 'strike', 'shield'],
  teaches: ['lord_imbalance_lore', 'multi_system_priority'],
};

// ---------- CODEX ----------
export const CODEX: CodexEntry[] = [
  { id: 'oxygenation_basics', title: 'Oxygenation: The First Breath', system: 'Air', level: 1, body: 'Every cell needs oxygen. When SpO₂ drops below 92%, the body shifts to anaerobic metabolism and tissue damage begins. Look for tripod posture, accessory muscle use, and pursed-lip breathing — the body shouting for air.' },
  { id: 'air_assessment', title: 'Air Assessment Priorities', system: 'Air', level: 2, body: 'Airway → Breathing → Circulation. Always. Before labs, before history, before the chart. Patent airway? Symmetrical chest rise? Adequate rate and depth? Tripod posture = severe distress.' },
  { id: 'circulation_basics', title: 'Circulation & Perfusion', system: 'River', level: 1, body: 'The heart pumps oxygen-rich blood to every tissue. Weak pulse, cool skin, pale appearance, and dizziness all signal failing perfusion. Pressure matters, but so does volume and pump strength.' },
  { id: 'energy_basics', title: 'Cellular Fuel', system: 'Energy', level: 1, body: 'Glucose is the brain’s only fuel. Below 70 mg/dL is hypoglycemia: shakiness, sweating, confusion. Treat fast — 15g of fast carbs, recheck in 15 minutes.' },
  { id: 'hypoglycemia_rules', title: 'The 15/15 Rule', system: 'Energy', level: 2, body: 'For hypoglycemia in a conscious patient: 15 grams of fast carbs (juice, glucose tabs), wait 15 minutes, recheck. Repeat up to 3 times. If unconscious — IV dextrose or IM glucagon.' },
  { id: 'infection_basics', title: 'Fever & the Immune Response', system: 'Fire', level: 1, body: 'Fever is the body’s alarm. It is also a weapon — many pathogens cannot survive elevated temperatures. Suppress fevers selectively, not reflexively, and never ignore the source.' },
  { id: 'sepsis_recognition', title: 'Recognizing Sepsis Early', system: 'Fire', level: 3, body: 'Sepsis kills through escalation. Fever + tachycardia + tachypnea + altered mental status = SIRS criteria. Add hypotension or organ dysfunction → severe sepsis. Lactate ≥ 2 is your warning bell. Hour-1 bundle: cultures, broad-spectrum antibiotics, fluids, lactate, reassess.' },
  { id: 'systemic_infection', title: 'When Infection Becomes Systemic', system: 'Fire', level: 3, body: 'Local infection contained by intact immune response stays local. When pathogens or their toxins enter the bloodstream, the body’s response becomes the danger: vasodilation, capillary leak, hypoperfusion. This is septic shock.' },
  { id: 'heart_failure_basics', title: 'The Weak Pump', system: 'River', level: 2, body: 'In heart failure, the pump cannot move forward what it receives. Blood backs up: into the lungs (crackles, dyspnea) and into the periphery (edema, weight gain). Daily weights, not fluid boluses.' },
  { id: 'fluid_balance', title: 'Fluid Balance & The Cardion Trap', system: 'River', level: 3, body: 'Fluids resuscitate shock — but drown a failing heart. Always ask: is this patient dry or wet? Crackles, JVD, edema, recent weight gain = wet. Aggressive fluids in Cardion = pulmonary edema.' },
  { id: 'dka_basics', title: 'Diabetic Ketoacidosis', system: 'Energy', level: 3, body: 'Without insulin, cells starve while glucose floods the blood. The body burns fat instead, releasing ketones — acidic. Kussmaul breathing blows off CO₂ to compensate. Treat with fluids first, then insulin, watching K⁺ closely.' },
  { id: 'insulin_safety', title: 'Insulin & Potassium', system: 'Storm', level: 4, body: 'Insulin drives potassium into cells along with glucose. In DKA, total body K⁺ is usually low even when serum levels look normal. Give insulin to a hypokalemic patient and rhythm collapse follows. Always check K⁺ first.' },
  { id: 'copd_basics', title: 'COPD: The Trapped Breath', system: 'Air', level: 2, body: 'COPD destroys the recoil of lungs and the cilia of airways. Patients work hardest to exhale, not inhale. Pursed-lip breathing creates positive pressure. Watch O₂ titration — too much can suppress drive in CO₂ retainers.' },
  { id: 'electrolyte_basics', title: 'The Storm Within', system: 'Storm', level: 2, body: 'Potassium, sodium, calcium, magnesium — these ions run every nerve, every muscle, every heartbeat. Imbalance presents as weakness, rhythm changes, paresthesias, confusion, or seizures.' },
  { id: 'potassium_rules', title: 'Potassium Extremes', system: 'Storm', level: 3, body: 'Normal K⁺: 3.5–5.0. Below 3.5 = weakness, U waves, ileus. Above 5.5 = peaked T waves, then loss of P waves, then sine wave, then arrest. Calcium gluconate stabilizes the membrane; insulin + glucose, bicarb, β-agonists shift it; kayexalate or dialysis remove it.' },
  { id: 'delirium_basics', title: 'Delirium vs Dementia', system: 'Mind', level: 2, body: 'Delirium is acute, fluctuating, and reversible. Dementia is chronic and progressive. Treat the cause: infection, medication, dehydration, hypoxia, pain, sleep deprivation. Reorient. Familiar faces. Daylight. Avoid restraints.' },
  { id: 'safety_first', title: 'Safety Comes First', system: 'Protection', level: 1, body: 'A confused patient who falls suffers two injuries — the original problem and the fall. Bed alarms, low beds, frequent checks, family at bedside. Restraints are last, not first.' },
  { id: 'lord_imbalance_lore', title: 'The Fading Core', system: 'Mind', level: 4, body: 'When multiple systems fail at once, prioritization becomes everything. ABCs first — but also: which problem will kill the patient in the next 5 minutes? Treat that. Then move down the list.' },
  { id: 'multi_system_priority', title: 'Multi-System Priority Framework', system: 'Mind', level: 4, body: 'Use ABC-D-E: Airway, Breathing, Circulation, Disability (neuro/glucose), Exposure (temperature/infection). When two systems are critical, treat the one that supports the others. Oxygen has no substitute. Glucose to a confused patient is a 30-second test that prevents disaster.' },
];

// ---------- BATTLE MECHANICS (always visible in the Codex — teaches strategy without the full math) ----------
export interface MechanicInfo { id: string; icon: string; title: string; body: string; }
export const BATTLE_MECHANICS: MechanicInfo[] = [
  { id: 'stability', icon: 'heart', title: 'Stability', body: "The patient's life gauge. If it hits 0 you lose the battle. Higher Stability also gives your team more Action Points each turn. Note: stabilizing gets weaker the closer to full it already is, so topping off from near-full does little — spend big heals when it's low." },
  { id: 'action_points', icon: 'flash', title: 'Action Points (AP)', body: 'Your budget of moves per turn. A stable patient earns more AP (up to 6); a crashing one drops to 2. Steadying the patient early lets you do more later.' },
  { id: 'corruption', icon: 'skull', title: 'Corruption (Enemy Health)', body: 'The disease\'s health bar — Strike it down to 0 to win. Left untreated, the disease worsens and Corruption grows. Bosses and later foes carry far more Corruption, so long fights need sustained damage.' },
  { id: 'clues', icon: 'search', title: 'Clues & Reveal', body: 'Hidden clues mask the true problem. Scout and Analyze skills reveal them, unlock gated treatments, and point you to the right counter. Assess before you strike — guessing wastes turns.' },
  { id: 'system_match', icon: 'color-palette', title: 'System Match', body: 'Every disease belongs to an elemental system (Air, Fire, River, Mind…). Treatments that match the disease\'s system hit noticeably harder. Some foes also have a weak system that takes bonus damage.' },
  { id: 'shield', icon: 'shield', title: 'Shield & Brace', body: 'Shields cut the next enemy attack: 50% halves the hit, 100% blocks it entirely. Brace right before a big incoming attack rather than wasting it on a light turn.' },
  { id: 'spread', icon: 'git-network', title: 'Spread', body: 'Some infections spread — worsening the disease at the end of the turn. Spread-blocking skills like Isolation Seal (or an Infection Control consult) stop the next spread once. Time them for when the disease is about to surge.' },
  { id: 'care_chain', icon: 'link', title: 'The Care Chain', body: 'Playing Scout → Stabilize → Counter in order completes a Care Chain for a big bonus. Following the nursing process is rewarded — rushing straight to attacks is not.' },
  { id: 'resistant_foes', icon: 'trending-up', title: 'Resistant & Relentless Foes', body: 'Bosses and late-game enemies resist stabilization — healing sticks less than the number shown — and can hold enormous Corruption. Lean on strong strikes and shields; you can\'t simply out-heal them.' },
  { id: 'wrong_treatment', icon: 'warning', title: 'Wrong Treatment Hurts', body: 'A poor-fit or unsafe action backfires: Stability drops and symptoms worsen. When you\'re unsure, Scout first — a wasted safe turn beats an active mistake.' },
  { id: 'treatment_field', icon: 'cloud', title: 'Treatment Field', body: 'Some wide-area treatments leave a lingering field over the whole ward — like a nebulizer mist — ticking extra damage on every enemy for a few beats after you cast it. Time your cast for when several foes are on the path.' },
  { id: 'response_confirmed', icon: 'checkmark-done', title: 'Response Confirmed', body: 'Reassessing right after a correctly-matched treatment lands validates the care plan: bonus Stability, Corruption cleanse, and your next strong hit is empowered. Reassess only pays off after a strong match — check your Clinical Cue first.' },
  { id: 'treatment_fatigue', icon: 'hourglass', title: 'Treatment Fatigue (Coming Soon)', body: 'A future mechanic: repeating the exact same treatment back-to-back will build fatigue and reduce its effect, rewarding varied care over one-button spam. Not yet active in this version.' },
];

// ---------- BUILDINGS ----------
export const BUILDINGS: Building[] = [
  { id: 'academy_of_healing', name: 'Academy of Healing', description: 'Trains your eye for vital signs and assessment.', unlocks: 'Basic Assessment +1 per battle', maxLevel: 5 },
  { id: 'library_of_knowledge', name: 'Library of Knowledge', description: 'Reveals deeper codex layers.', unlocks: 'Unlock Codex Level 3 entries', maxLevel: 5 },
  { id: 'hall_of_heroes', name: 'Hall of Heroes', description: 'Recruits and trains healer heroes.', unlocks: '+1 hero slot per level', maxLevel: 5 },
  { id: 'apothecary', name: 'Apothecary', description: 'Crafts remedies and antidotes.', unlocks: 'Consumable items per shift', maxLevel: 5 },
];

// ---------- DAILY SHIFT ENCOUNTER POOL ----------
export function pickDailyShift(): { encounters: Enemy[]; boss: Enemy } {
  // Simple deterministic-ish pick: shuffle 3 starter enemies and use boss
  const starters = [
    ENEMIES.find(e => e.id === 'air_sprite')!,
    ENEMIES.find(e => e.id === 'river_sludge')!,
    ENEMIES.find(e => e.id === 'energy_lock')!,
    ENEMIES.find(e => e.id === 'fire_imp')!,
    ENEMIES.find(e => e.id === 'mind_fog')!,
  ];
  const advanced = [
    ENEMIES.find(e => e.id === 'septara_seed')!,
    ENEMIES.find(e => e.id === 'cardion_echo')!,
    ENEMIES.find(e => e.id === 'glycora_spark')!,
    ENEMIES.find(e => e.id === 'pulmora_wisp')!,
    ENEMIES.find(e => e.id === 'electrox_flicker')!,
  ];
  const shuf = <T,>(arr: T[]) => [...arr].sort(() => Math.random() - 0.5);
  const picks = [...shuf(starters).slice(0, 2), shuf(advanced)[0]];
  return { encounters: picks, boss: BOSS_LORD_IMBALANCE };
}

export const APTITUDE_INFO: Record<string, { title: string; element: string; color: string; passive: string; icon: string }> = {
  guardian: { title: 'Guardian', element: 'River', color: '#059669', passive: 'Bonus stability recovery in battle.', icon: 'shield-checkmark' },
  sage: { title: 'Sage', element: 'Mind', color: '#E5E7EB', passive: 'Reveals one extra clue per encounter.', icon: 'eye' },
  warden: { title: 'Warden', element: 'Protection', color: '#D4AF37', passive: 'Prevents one minor deterioration per battle.', icon: 'lock-closed' },
  weaver: { title: 'Weaver', element: 'Storm', color: '#BEF264', passive: 'Predicts an upcoming complication.', icon: 'sparkles' },
};
