/**
 * battleAssist.ts — Early-failure assistance system.
 *
 * DESIGN RULES (from spec):
 *   1. Scenario-authored, not generated by the battle UI.
 *      mentorText, highlightActionId, and highlightTargetId live in
 *      battleAssistConfigs.ts — the battle UI renders what it receives.
 *   2. Pure functions only — no React state, no side effects.
 *   3. consecutiveFailures persists with the specific encounter, not globally.
 *      In practice this is failure_counts[enemyId] which resets on win and
 *      increments on loss — already per-enemy in PlayerState.
 */

// ── Types ─────────────────────────────────────────────────────────────────────

/**
 * A single authored hint rule that activates once the player has failed
 * the encounter at least `afterConsecutiveFailures` times in a row.
 */
export interface BattleAssistRule {
  afterConsecutiveFailures: number;

  /** Mentor guidance text shown to the player. */
  mentorText: string;

  /**
   * Optional existing battle action identifier.
   * The UI may highlight the corresponding action button.
   */
  highlightActionId?: string;

  /**
   * Optional existing target/threat id.
   * The UI may highlight the corresponding threat tile or enemy indicator.
   */
  highlightTargetId?: string;
}

/**
 * Full assist configuration for one encounter or chapter.
 *
 * `freeBattleRetry`: battle retry costs nothing additional.
 * IMPORTANT: do NOT refund Journey stamina already spent moving onto the tile.
 */
export interface BattleAssistConfig {
  enabled: boolean;

  /**
   * Battle retry costs 0 additional Journey stamina.
   *
   * Canonical stamina rule:
   *   Moving onto a map tile costs 1 stamina.          ← spent on entry, gone.
   *   Starting the battle costs nothing extra.
   *   Failing the battle → retry costs 0.              ← this flag enforces it.
   *   Failing again      → retry still costs 0.
   *
   * MUST NOT refund the 1 stamina already spent entering the tile.
   * Refunding would let players exploit failure as a stamina-recovery loop.
   */
  freeBattleRetry: boolean;

  /** Ordered list of authored hint rules. */
  rules: BattleAssistRule[];
}

/**
 * Minimal per-encounter attempt state.
 *
 * Kept as a plain data object so it can be embedded in JourneyTile or
 * any other persistence layer without coupling to the store.
 */
export interface EncounterAttemptState {
  consecutiveFailures: number;
}

// ── Pure functions ────────────────────────────────────────────────────────────

/**
 * Returns the most specific authored rule that applies given the current
 * consecutive failure count, or null when no rule applies.
 *
 * Algorithm: keep all rules whose threshold ≤ consecutiveFailures, then
 * return the one with the highest threshold (most specific / most helpful).
 *
 * Returns null when:
 *   • config is undefined (encounter has no assist config)
 *   • config.enabled is false
 *   • consecutiveFailures is 0 (player hasn't failed yet)
 *   • no rule threshold has been reached
 */
export function getBattleAssistRule(
  config: BattleAssistConfig | undefined,
  consecutiveFailures: number,
): BattleAssistRule | null {
  if (!config?.enabled || consecutiveFailures <= 0) return null;

  const eligible = config.rules
    .filter((rule) => consecutiveFailures >= rule.afterConsecutiveFailures)
    .sort((a, b) => b.afterConsecutiveFailures - a.afterConsecutiveFailures);

  return eligible[0] ?? null;
}

/**
 * Records a failure for this encounter by incrementing consecutiveFailures.
 * Pure — returns a new state object.
 */
export function recordEncounterFailure(
  state: EncounterAttemptState,
): EncounterAttemptState {
  return { ...state, consecutiveFailures: state.consecutiveFailures + 1 };
}

/**
 * Records a victory for this encounter by resetting consecutiveFailures to 0.
 * Pure — returns a new state object.
 */
export function recordEncounterVictory(
  state: EncounterAttemptState,
): EncounterAttemptState {
  return { ...state, consecutiveFailures: 0 };
}
