// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/clinica-layout/PrologueLayoutDiagram.tsx": () => import("../components/mockups/clinica-layout/PrologueLayoutDiagram.tsx")
};
