// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/journey-map-aesthetics/JourneyMapAesthetics.tsx": () => import("../components/mockups/journey-map-aesthetics/JourneyMapAesthetics.tsx"),
  "./components/mockups/main-hub/Current.tsx": () => import("../components/mockups/main-hub/Current.tsx"),
  "./components/mockups/main-hub/JourneyMap.tsx": () => import("../components/mockups/main-hub/JourneyMap.tsx"),
  "./components/mockups/prologue-vn-positions/CoverContainExplainer.tsx": () => import("../components/mockups/prologue-vn-positions/CoverContainExplainer.tsx"),
  "./components/mockups/prologue-vn-positions/SIRevealPositions.tsx": () => import("../components/mockups/prologue-vn-positions/SIRevealPositions.tsx"),
  "./components/mockups/prologue-vn-positions/ScenePositions.tsx": () => import("../components/mockups/prologue-vn-positions/ScenePositions.tsx"),
  "./components/mockups/prologue-vn-positions/TacticalWarningPositions.tsx": () => import("../components/mockups/prologue-vn-positions/TacticalWarningPositions.tsx"),
  "./components/mockups/clinica-layout/PrologueLayoutDiagram.tsx": () => import("../components/mockups/clinica-layout/PrologueLayoutDiagram.tsx")
};
